version: '3.5'

services:
  backend:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: '.'
      args:
        uid: 1000
    ports:
      - ${API_PORT}:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: ${DB_PASSWORD_ROOT}
      ports:
        - ${PMA_PORT}:80
      volumes:
        - /sessions